### ISSUE TITLE
Android向けにビルドするとビルドエラーが発生する

### ISSUE THREAD

**Issue by shuhei-yamada** [sassembla/Miyamasu#1]
環境
Unity 2017.2.0f3

エラーログ
``Assets/MiyamasuTestRunner/Runtime/Generated/GeneratedTestEntryPoints.cs(2,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?  
``
``
Assets/MiyamasuTestRunner/Runtime/Miyamasu2UnityTestConverter.cs(7,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?  
``
``
Assets/MiyamasuTestRunner/Runtime/MiyamasuTestRuntimeRunner.cs(10,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?  
``

どうやら、unitypackageでMiyamasuをインストールするとエラーが出るみたいです。
リポジトリをzipでダウンロードしてUnityで開いてビルドするとエラーなくビルドできました。

**Comment by sassembla** [comment]
this is caused by unnecessary generated test files are contained in unitypackage.
and I wrote some instruction in README.md for install.

fixed 22211e7b825f5eed06eafbcc05acec060389551e .

thank you for using Miyamasu!
